swagger: '2.0'
info:
  version: '1.0'
  title: Sunnah.com API
  description: |-
    Sunnah.com API offers access to verified data of collections of hadith of the Prophet (SAWS). Here you will find a list of the available endpoints in our REST API.

    You will need an API key to access this data, which you may request from https://sunnah.com/contact.
  contact:
    name: Sunnah.com
    url: 'https://sunnah.com/contact'
    email: sunnah@iman.net
host: api.sunnah.com
schemes:
  - https
produces:
  - application/json
securityDefinitions:
  APIKey:
    name: X-API-Key
    type: apiKey
    in: header
security:
  - APIKey: []
basePath: /v1/
paths:
  /hadiths/random:
    get:
      summary: Get a randomly selected hadith
      description: ''
      responses:
        '200':
          description: A randomly selected hadith
          schema:
            $ref: '#/definitions/Hadith'
  /collections:
    get:
      summary: Get the list of collections
      description: ''
      responses:
        '200':
          description: Paginated list of available collections
          schema:
            type: object
            allOf:
              - properties:
                  data:
                    type: array
                    items:
                      $ref: '#/definitions/Collection'
              - $ref: '#/definitions/PaginatedResponse'
      parameters:
        - $ref: '#/parameters/limit'
        - $ref: '#/parameters/page'
  '/collections/{collectionName}/books/{bookNumber}/chapters':
    get:
      summary: Get the list of chapters of a book for a collection
      description: ''
      responses:
        '200':
          description: Paginated list of chapters of a book of a collection
          schema:
            type: object
            allOf:
              - properties:
                  data:
                    type: array
                    items:
                      $ref: '#/definitions/Chapter'
              - $ref: '#/definitions/PaginatedResponse'
      parameters:
        - in: path
          name: collectionName
          description: name of collection
          required: true
          type: string
        - in: path
          name: bookNumber
          description: number of the book
          required: true
          type: string
        - $ref: '#/parameters/limit'
        - $ref: '#/parameters/page'
  '/collections/{collectionName}/books/{bookNumber}/hadiths':
    get:
      summary: Get the list of hadith of a book for a collection
      description: ''
      responses:
        '200':
          description: Paginated list of hadiths of a book of a collection
          schema:
            type: object
            allOf:
              - properties:
                  data:
                    type: array
                    items:
                      $ref: '#/definitions/Hadith'
              - $ref: '#/definitions/PaginatedResponse'
      parameters:
        - in: path
          name: collectionName
          description: name of collection
          required: true
          type: string
        - in: path
          name: bookNumber
          description: number of the book
          required: true
          type: string
        - $ref: '#/parameters/limit'
        - $ref: '#/parameters/page'
  '/collections/{collectionName}/hadiths/{hadithNumber}':
    get:
      summary: Get a hadith of a collection
      description: ''
      responses:
        '200':
          description: Hadith of a book of a collection
          schema:
            $ref: '#/definitions/Hadith'
      parameters:
        - in: path
          name: collectionName
          description: name of collection
          required: true
          type: string
        - in: path
          name: hadithNumber
          description: number of the hadith
          required: true
          type: string
  '/collections/{collectionName}/books/{bookNumber}':
    get:
      summary: Get a book of a collection
      description: ''
      responses:
        '200':
          description: A book of a collection
          schema:
            type: array
            items:
              $ref: '#/definitions/Book'
      parameters:
        - in: path
          name: collectionName
          description: name of collection
          required: true
          type: string
        - in: path
          name: bookNumber
          description: number of the book
          required: true
          type: string
  '/collections/{collectionName}/books':
    get:
      summary: Get the list of books for a collection
      description: ''
      responses:
        '200':
          description: Paginated list of available books of a collection
          schema:
            type: object
            allOf:
              - properties:
                  data:
                    type: array
                    items:
                      $ref: '#/definitions/Book'
              - $ref: '#/definitions/PaginatedResponse'
      parameters:
        - in: path
          name: collectionName
          description: name of collection
          required: true
          type: string
        - $ref: '#/parameters/limit'
        - $ref: '#/parameters/page'
  '/collections/{collectionName}':
    get:
      summary: Get collection by name
      description: ''
      responses:
        '200':
          description: A collection
          schema:
            $ref: '#/definitions/Collection'
      parameters:
        - in: path
          name: collectionName
          description: name of collection
          required: true
          type: string
parameters:
  limit:
    in: query
    name: limit
    description: Maximum number of items
    required: false
    type: integer
    default: 50
    maximum: 100
  page:
    in: query
    name: page
    description: Offset for pagination
    required: false
    type: integer
    default: 1
definitions:
  PaginatedResponse:
    type: object
    properties:
      total:
        type: integer
      limit:
        type: integer
      previous:
        type: integer
      next:
        type: integer
  Hadith:
    type: object
    properties:
      collection:
        type: string
        description: "the Collection's name"
      bookNumber:
        type: string
        description: The number of the book this hadith belongs to
      chapterId:
        type: string
        description: The id of the chapter this hadith belongs to
      hadithNumber:
        type: integer
      hadith:
        type: array
        description: Language specific data of the hadith
        items:
          type: object
          properties:
            lang:
              type: string
            chapterNumber:
              type: string
            chapterTitle:
              type: string
            urn:
              type: string
            body:
              type: string
            grade:
              type: string
  Chapter:
    properties:
      bookNumber:
        type: string
        description: The number of the book this chapter belongs to
      chapterId:
        type: string
        description: The id of the chapter
      chapter:
        type: array
        description: Language specific data of the chapter
        items:
          type: object
          properties:
            lang:
              type: string
            chapterNumber:
              type: string
            chapterTitle:
              type: string
            intro:
              type: string
            ending:
              type: string
  Book:
    properties:
      bookNumber:
        type: string
        description: "the Book's name"
      book:
        type: array
        description: Language specific data of the book
        items:
          type: object
          properties:
            lang:
              type: string
            name:
              type: string
      hadithStartNumber:
        type: integer
        description: The first hadith number that is available in this book
      hadithEndNumber:
        type: integer
        description: The last hadith number that is available in this book
      numberOfHadith:
        type: integer
        description: Total number of available hadith in this book
  Collection:
    properties:
      name:
        type: string
        description: "the Collection's name"
      hasBooks:
        type: boolean
        description: whether the Collection has books or not
      hasChapters:
        type: boolean
        description: whether the Collection has chapters or not
      collection:
        type: array
        description: Language specific data of the collection
        items:
          type: object
          properties:
            lang:
              type: string
            title:
              type: string
            shortIntro:
              type: string
      totalHadith:
        type: integer
        description: Total number of hadith in the collection
      totalAvailableHadith:
        type: integer
        description: Total number of available hadith in the collection
